spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: eurekaServerDev
server:
  port: 7001
  # Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false # 表示是否想在注册中心注册自己
    fetch-registry: false # 为false表示自己为注册中心
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
      # 默认地址 http://localhost:8761/eureka/
      # 集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
spring:
  profiles: test
  application:
    name: eurekaServerTest
server:
  port: 7001
  # Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false # 表示是否想在注册中心注册自己
    fetch-registry: false # 为false表示自己为注册中心
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个defaultZone地址
      # 默认地址 http://localhost:8761/eureka/
      # 集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
